# Separate BFF Pipeline
# Triggers only when BFF or client files change

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - BFF/**
      - client/**

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  appName: 'apelamay-int-bff'
  azureSubscription: 'Azure-Apelamay-Int'
  nodeVersion: '20.x'

stages:
  - stage: Build
    displayName: 'Build BFF and React'
    jobs:
      - job: BuildBFF
        displayName: 'Build and Package'
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js $(nodeVersion)'
            inputs:
              versionSpec: '$(nodeVersion)'

          - script: |
              echo "Installing dependencies..."
              cd client
              npm ci
            displayName: 'Install npm packages'          - script: |
              echo "Building React application..."
              cd client
              npm run build
              echo "React build completed"
              ls -la ../BFF/wwwroot
            displayName: 'Build React App'
            
          - task: UseDotNet@2
            displayName: 'Use .NET 9.0'
            inputs:
              version: '9.0.x'

          - task: DotNetCoreCLI@2
            displayName: 'Restore BFF'
            inputs:
              command: 'restore'
              projects: 'BFF/BFF.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'Build BFF'
            inputs:
              command: 'build'
              projects: 'BFF/BFF.csproj'
              arguments: '--configuration $(buildConfiguration) --no-restore'

          - task: DotNetCoreCLI@2
            displayName: 'Publish BFF'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: 'BFF/BFF.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build'
              zipAfterPublish: true          - task: PublishPipelineArtifact@1
            displayName: 'Publish Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'bff-drop'

  - stage: DeployProduction
    displayName: 'Deploy to Production'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: DeployBFF
        displayName: 'Deploy BFF'
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download BFF Artifact'
            inputs:
              artifactName: 'bff-drop'
              downloadPath: '$(Pipeline.Workspace)'

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: '$(appName)'
              package: '$(Pipeline.Workspace)/**/*.zip'
              deploymentMethod: 'zipDeploy'

          - task: PowerShell@2
            displayName: 'Health Check'
            inputs:
              targetType: 'inline'
              script: |
                Start-Sleep -Seconds 30
                $response = Invoke-WebRequest -Uri "https://$(appName).azurewebsites.net" -UseBasicParsing
                if ($response.StatusCode -eq 200) {
                  Write-Host "✅ BFF deployed successfully"
                  Write-Host "🌐 URL: https://$(appName).azurewebsites.net"
                } else {
                  Write-Error "❌ Health check failed"
                  exit 1
                }
