# Separate API Pipeline
# Triggers only when API-related files change

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - API/**
      - Application/**
      - Domain/**
      - Infrastructure/**
      - Persistence/**

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  basePrefix: 'apelamay'
  azureSubscription: 'Azure-Apelamay-Int'

stages:
  - stage: Build
    displayName: 'Build API'
    jobs:
      - job: BuildAPI
        displayName: 'Build and Test'
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET 9.0'
            inputs:
              version: '9.0.x'

          - task: DotNetCoreCLI@2
            displayName: 'Restore Dependencies'
            inputs:
              command: 'restore'
              projects: 'API/API.csproj'          
          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              command: 'build'
              projects: 'API/API.csproj'
              arguments: '--configuration $(buildConfiguration) --no-restore'

          - task: DotNetCoreCLI@2
            displayName: 'Run Tests'
            inputs:
              command: 'test'
              projects: '**/*Tests.csproj'
              arguments: '--configuration $(buildConfiguration) --no-build'
            continueOnError: true

          - task: DotNetCoreCLI@2
            displayName: 'Publish'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: 'API/API.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build'
              zipAfterPublish: true

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'api-drop'  # Deploy to INT Environment
  - stage: DeployINT
    displayName: 'Deploy to INT'
    dependsOn: Build
    condition: |
      and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
          eq(variables['Build.SourceBranch'], 'refs/heads/main')
        )
      )
    variables:
      environment: 'int'
      appName: '$(basePrefix)-$(environment)-api'
    jobs:
      - deployment: DeployAPI
        displayName: 'Deploy API to INT'
        environment: 'INT'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download API Artifact'
                  inputs:
                    artifactName: 'api-drop'
                    downloadPath: '$(Pipeline.Workspace)'

                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure App Service'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: 'webApp'
                    appName: '$(appName)'
                    package: '$(Pipeline.Workspace)/**/*.zip'
                    deploymentMethod: 'zipDeploy'

                - task: PowerShell@2
                  displayName: 'Health Check'
                  inputs:
                    targetType: 'inline'
                    script: |
                      Start-Sleep -Seconds 30
                      $response = Invoke-WebRequest -Uri "https://$(appName).azurewebsites.net/api/activities" -UseBasicParsing
                      if ($response.StatusCode -eq 200) {
                        Write-Host "✅ API deployed successfully to INT"
                      } else {
                        Write-Error "❌ Health check failed"
                        exit 1
                      }  # Deploy to UAT Environment
  - stage: DeployUAT
    displayName: 'Deploy to UAT'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/uat'))
    variables:
      environment: 'uat'
      appName: '$(basePrefix)-$(environment)-api'
    jobs:
      - deployment: DeployAPI
        displayName: 'Deploy API to UAT'
        environment: 'UAT'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download API Artifact'
                  inputs:
                    artifactName: 'api-drop'
                    downloadPath: '$(Pipeline.Workspace)'

                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure App Service'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: 'webApp'
                    appName: '$(appName)'
                    package: '$(Pipeline.Workspace)/**/*.zip'
                    deploymentMethod: 'zipDeploy'

                - task: PowerShell@2
                  displayName: 'Health Check'
                  inputs:
                    targetType: 'inline'
                    script: |
                      Start-Sleep -Seconds 30
                      $response = Invoke-WebRequest -Uri "https://$(appName).azurewebsites.net/api/activities" -UseBasicParsing
                      if ($response.StatusCode -eq 200) {
                        Write-Host "✅ API deployed successfully to UAT"
                      } else {
                        Write-Error "❌ Health check failed"
                        exit 1
                      }  # Deploy to PROD Environment
  - stage: DeployPROD
    displayName: 'Deploy to PROD'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      environment: 'prod'
      appName: '$(basePrefix)-$(environment)-api'
    jobs:
      - deployment: DeployAPI
        displayName: 'Deploy API to PROD'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download API Artifact'
                  inputs:
                    artifactName: 'api-drop'
                    downloadPath: '$(Pipeline.Workspace)'

                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure App Service'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: 'webApp'
                    appName: '$(appName)'
                    package: '$(Pipeline.Workspace)/**/*.zip'
                    deploymentMethod: 'zipDeploy'

                - task: PowerShell@2
                  displayName: 'Health Check'
                  inputs:
                    targetType: 'inline'
                    script: |
                      Start-Sleep -Seconds 30
                      $response = Invoke-WebRequest -Uri "https://$(appName).azurewebsites.net/api/activities" -UseBasicParsing
                      if ($response.StatusCode -eq 200) {
                        Write-Host "✅ API deployed successfully to PROD"
                      } else {
                        Write-Error "❌ Health check failed"
                        exit 1
                      }
